// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmivzeEWhNl4gUUIFQ_HYV9Kl1GasZFsk',
    appId: '1:104356230641:web:77acc9ca66784ce611c050',
    messagingSenderId: '104356230641',
    projectId: 'ezserve-97bbf',
    authDomain: 'ezserve-97bbf.firebaseapp.com',
    storageBucket: 'ezserve-97bbf.firebasestorage.app',
    measurementId: 'G-DC4TQRGJER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1lJKO_kkBpvYutBtMkRyWg2EEsibahp8',
    appId: '1:104356230641:android:d5e91fd965c4823e11c050',
    messagingSenderId: '104356230641',
    projectId: 'ezserve-97bbf',
    storageBucket: 'ezserve-97bbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZjlCEn2a8WU4qPJMlf7dYUmSzNUDM8s',
    appId: '1:104356230641:ios:1f2d7a62c8404fff11c050',
    messagingSenderId: '104356230641',
    projectId: 'ezserve-97bbf',
    storageBucket: 'ezserve-97bbf.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZjlCEn2a8WU4qPJMlf7dYUmSzNUDM8s',
    appId: '1:104356230641:ios:1f2d7a62c8404fff11c050',
    messagingSenderId: '104356230641',
    projectId: 'ezserve-97bbf',
    storageBucket: 'ezserve-97bbf.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmivzeEWhNl4gUUIFQ_HYV9Kl1GasZFsk',
    appId: '1:104356230641:web:fc0f5ea655ddb94d11c050',
    messagingSenderId: '104356230641',
    projectId: 'ezserve-97bbf',
    authDomain: 'ezserve-97bbf.firebaseapp.com',
    storageBucket: 'ezserve-97bbf.firebasestorage.app',
    measurementId: 'G-ZPRMSP716R',
  );
}
